apiVersion: v1
kind: Pod
metadata:
  name: happy-lichterman
  namespace: default
  labels: {app: nextflow, runName: happy-lichterman}
spec:
  restartPolicy: Never
  containers:
  - name: happy-lichterman
    image: nextflow/nextflow:24.07.0-edge
    command: [/bin/bash, -c, source /etc/nextflow/init.sh; nextflow run Nine-s/download_sra/download_data.nf
        -name happy-lichterman -r master]
    env:
    - {name: NXF_WORK, value: /workspace/ninon/work}
    - {name: NXF_ASSETS, value: /workspace/projects}
    - {name: NXF_EXECUTOR, value: k8s}
    - {name: NXF_ANSI_LOG, value: 'false'}
    volumeMounts:
    - {name: vol-1, mountPath: /workspace}
    - {name: vol-2, mountPath: /etc/nextflow}
  serviceAccountName: default
  securityContext: {runAsUser: 0}
  volumes:
  - name: vol-1
    persistentVolumeClaim: {claimName: nextflow-ninon}
  - name: vol-2
    configMap: {name: nf-config-8770892c}
